config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.save
    redirect_to articles_path(@article)
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @article.update(article_params)
    redirect_to articles_path(@article)
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path(@article)
  end

  private

  def article_params
    params.require(:article).permit(:title, :content)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/edit.html.erb
<div class="container">

  <h1>Edit article</h1>

  <div>
  <%= form_for(@article, :html => {:class => "form-group"}) do |f| %>
      <%= f.label :title %>
      <%= f.text_field :title, :class => "form-control" %>
      <%= f.label :content %>
      <%= f.text_area :content, :class => "form-control" %>
      <%= f.submit class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/articles/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2">
      <% @articles.each do |article| %>
        <div class="article">
          <h2>
            <a><%= link_to article.title, article_path(article), :id => "article-title" %></a>
          </h2>
          <p> <%= article.content %> </p>
           </div>
          <% end %>

    </div>
  </div>
</div>

app/views/articles/new.html.erb
<div class="container">
    <div class="row">
      <div class="col-sm-8 col-sm-offset-2">

        <h1>New article</h1>

    <div>
      <%= form_for(@article, :html => {:class => "form-group"}) do |f| %>
        <%= f.label :title%>
        <%= f.text_field :title, :class => "form-control"%>

        <%= f.label :content %>
        <%= f.text_area :content, :class => "form-control" %>
        <%= f.submit class: 'btn btn-primary' %>
        <% end %>
    </div>


      </div>
    </div>
  </div>

app/views/articles/show.html.erb
<div class="container">
    <div class="row">
      <div class="col-sm-8 col-sm-offset-2">



<article>
  <h1>
     <%= @article.title %> <%= link_to '', article_path(@article), method: :delete, :id => "logo-size", :class => "far fa-trash-alt", data: { confirm: "Are you sure?" } %> <%= link_to '', edit_article_path, :id => "logo-size", :class => "fas fa-pencil-alt" %>
  </h1>

  <hr>
  <p>Adipisci quis et recusandae et quae. Quidem delectus architecto. Voluptatem aut harum. Inventore delectus est numquam.</p>

<p><img src="http://lorempixel.com/800/300/city/" alt="" /></p>


<p><%= @article.content %></p>

</article>


      </div>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
  </head>

  <body>
<!-- Image and text -->
    <nav class="navbar navbar-light bg-light">
      <a class="navbar-brand" href="#">
        <img src="http://www.myiconfinder.com/uploads/iconsets/256-256-7133fd5ca2feec0c855fb428218dbd94.png" width="30" height="30" class="d-inline-block align-top" alt=""><%= link_to 'NewsPaper', articles_path, :id => "news-logo" %>
      </a>
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><%= link_to 'New Artcile', new_article_path %></button>
    </nav>

    <%= yield %>
  </body>
</html>